var PF_VERSION="2014-04-16-070132216",pfMod=window.pfMod||function(d,l){var f=d.document.location.protocol,k={environment:"production",protocol:f,dir:"ltr",usingBM:!1,hosts:{cdn:"https:"==f?"https://d3nekkt1lmmhms.cloudfront.net":"http://cdn.printnicer.com",pf:f+"//www.printfriendly.com",ds:f+"//ds.printfriendly.com",pdf:f+"//pdf.printfriendly.com",email:f+"//email-srv.printfriendly.com",tracker:f+"//log.printfriendly.com",page:d.location.host},domains:{page:d.location.host.split(":")[0].split("www.").pop()}},
c={isReady:!1,readyBound:!1,addStyles:function(){var a=document.getElementsByTagName("head")[0],b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText="body * { z-index: 0 !important; }":b.appendChild(document.createTextNode("body * { z-index: 0 !important; }"));a.appendChild(b)},setWidthOfImages:function(){for(var a=document.getElementsByTagName("img"),b=0;b<a.length;b++){var d=a[b];d.width=d.width}},convertRelativetoAbsolute:function(a){for(var b=document.getElementsByTagName(a),
d=0;d<b.length;d++){var c=b[d];try{"img"===a?c.src=c.src:c.href=c.href}catch(e){}}},removeScripts:function(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++)"undefined"!==typeof a[b].src&&-1!==a[b].src.indexOf("printfriendly")||!a[b].parentNode||(a[b].parentNode.removeChild(a[b]),b--)},processElements:function(){for(var a,b,c=document.body.getElementsByTagName("*"),e=0;e<c.length;e++)try{b=c[e],-1!=="|link|style|iframe|ins|noscript|object|embed|select|".indexOf("|"+b.nodeName.toLowerCase()+
"|")?(b.parentNode.removeChild(b),e--):(a="NA",a=b.currentStyle?b.currentStyle.display:d.getComputedStyle(b,null).getPropertyValue("display"),"none"===a&&(b.className+=" hidden-originally"))}catch(f){}},ready:function(){if(!c.isReady){if(!document.body)return setTimeout(c.ready,13);c.isReady=!0;c.readyFunc.call()}},doScrollCheck:function(){if(!c.isReady){try{document.documentElement.doScroll("left")}catch(a){return setTimeout(c.doScrollCheck,50)}c.detach();c.ready()}},detach:function(){document.addEventListener?
(document.removeEventListener("DOMContentLoaded",c.completed,!1),d.removeEventListener("load",c.completed,!1)):document.attachEvent&&"complete"===document.readyState&&(document.detachEvent("onreadystatechange",c.completed),d.detachEvent("onload",c.completed))},completed:function(a){if(document.addEventListener||"load"===a.type||"complete"===document.readyState)c.detach(),c.ready()},bindReady:function(){if(!c.readyBound){c.readyBound=!0;if("complete"===document.readyState)return c.ready();if(document.addEventListener)document.addEventListener("DOMContentLoaded",
c.completed,!1),d.addEventListener("load",c.completed,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",c.completed);d.attachEvent("onload",c.completed);var a=!1;try{a=null==d.frameElement&&document.documentElement}catch(b){}a&&a.doScroll&&c.doScrollCheck()}}},domReady:function(a){this.readyFunc=a;this.bindReady()}},h={headerImageUrl:d.pfHeaderImgUrl,headerTagline:d.pfHeaderTagline,imageDisplayStyle:d.pfImageDisplayStyle,customCSSURL:d.pfCustomCSS,disableClickToDel:d.pfdisableClickToDel,
disablePDF:d.pfDisablePDF,disablePrint:d.pfDisablePrint,disableEmail:d.pfDisableEmail,hideImages:d.pfHideImages},e={version:PF_VERSION,initialized:!1,messages:[],errors:[],init:function(a){try{this.initialized=!0,this.configure(a),this.setVariables(),this.detectBrowser(),this.startIfNecessary(),d.print=this.start}catch(b){g.log(b)}},configure:function(a){this.config=k;if(a){this.config.environment="development";for(var b in a.hosts)this.config.hosts[b]=a.hosts[b]}},startIfNecessary:function(){(d.pfstyle||
-1!=this.config.urls.page.indexOf("pfstyle=wp"))&&this.start()},start:function(){e.isRedirectNecessary()?e.redirect():c.domReady(function(){try{e.startTime=(new Date).getTime(),e.cacheBodyHTML(),e.createMask(),e.loadCore()}catch(a){g.log(a)}})},setVariables:function(){var a,b="production"===this.config.environment?this.version:Math.random();this.config.urls={js:{jquery:f+"//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js",jqueryBackup:this.config.hosts.cdn+"/javascripts/common/jquery/1.11.0/jquery.min.js",
core:this.config.hosts.cdn+"/versions/"+this.version+"/js/core.js?_="+b,algo:this.config.hosts.cdn+"/versions/"+this.version+"/js/algo.js?_="+b},css:{page:this.config.hosts.cdn+"/versions/"+this.version+"/css/main.css?_="+b},pdfMake:this.config.hosts.pdf+"/pdfs/make",email:this.config.hosts.email+"/email/new"};try{a=top.location.href}catch(c){a=d.location.href}this.config.urls.page=a;this.userSettings=h;!d.pfstyle||"bk"!==d.pfstyle&&"nbk"!==d.pfstyle&&"cbk"!==d.pfstyle||(this.config.usingBM=!0)},
detectBrowser:function(){this.browser={};var a=navigator.appVersion;-1!==a.indexOf("MSIE")?(this.browser.version=parseFloat(a.split("MSIE")[1]),this.browser.isIE=!0):this.browser.isIE=!1},detectPlatforms:function(){var a=document.styleSheets,b=/wp-content/i,c=/blogger.com/i;if("wsite"===d.STYLE_PREFIX)this.config.isWeebly=!0;else for(var e=0;e<a.length;e++)if(null!==a[e].href&&-1!==a[e].href.search(b)){this.config.isWP=!0;break}else if(null!==a[e].href&&-1!==a[e].href.search(c)){this.config.isBlogger=
!0;break}},createIframe:function(a){a=a.createElement("iframe");a.src="javascript:false";a.frameBorder="0";a.allowTransparency="true";return a},loadHtmlInIframe:function(a,b,d){var c;try{c=b.contentWindow.document}catch(e){a=a.domain,b.src="javascript:var d=document.open();d.domain='"+a+"';void(0);",c=b.contentWindow.document}c.write(d);c.close()},redirect:function(){var a=["redirect=1","url="+encodeURIComponent(top.location.href)],b;for(b in h)"undefined"!==typeof h[b]&&a.push(b+"="+encodeURIComponent(h[b]));
top.location.replace(this.config.hosts.pf+"/print/?"+a.join("&"))},isRedirectNecessary:function(){try{return navigator.userAgent.match(/(iphone|ipad|ipod|android|opera.mini)/i)||this.browser.isIE&&8>this.browser.version||"undefined"!==typeof $&&$.jcarousel&&this.browser.isIE||this.browser.isIE&&9>this.browser.version&&"skinnytaste.com"===this.config.domains.page?!0:!1}catch(a){return!1}},createMask:function(){var a=document.createElement("div");a.innerHTML='<div id="pf-mask" style="z-index: 2147483627!important; position: fixed !important; top: 0pt !important; left: 0pt !important; background-color: rgb(0, 0, 0) !important; opacity: 0.8 !important;filter:progid:DXImageTransform.Microsoft.Alpha(opacity=80); height: 100% !important; width: 100% !important;"></div>';
document.body.appendChild(a.firstChild)},cacheBodyHTML:function(){c.addStyles();c.setWidthOfImages();c.convertRelativetoAbsolute("a");c.convertRelativetoAbsolute("img");c.removeScripts();c.processElements();e.detectPlatforms();e.bodyCache='<div id="'+document.body.id+'" class="'+document.body.className+' pf-body-cache">'+document.body.innerHTML+"</div>";document.body.innerHTML="<p></p>"},refresh:function(){var a=e.config.urls.page.replace("pfstyle=wp","").replace(/#(.*)$/,"");try{return document.body.innerHTML=
'<div style="position:absolute; top:0; bottom:0; left:0; right:0; padding:10%; text-align:center; background:#333;">&nbsp;</div>',-1===e.config.urls.page.indexOf("pfstyle")?d.top.location.reload():d.top.location.href=a,!1}catch(b){setTimeout(function(){d.top.location.replace(a)},100)}},removeDoubleSemiColon:function(a){return a.replace(/;{2}/g,";")},loadCore:function(){var a='<!DOCTYPE html><html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><script src="'+this.config.urls.js.jquery+
'">\x3c/script><script src="'+this.config.urls.js.core+'">\x3c/script><link media="screen" type="text/css" rel="stylesheet" href="'+this.config.urls.css.page+'"></head><body onload="core.init();"></body>',b=this.createIframe(document);b.id="pf-core";document.body.appendChild(b);b.style.cssText=this.removeDoubleSemiColon(b.style.cssText+";width: 100% !important;max-width:100% !important;height: 100% !important; display: block !important; overflow: hidden !important; position: absolute !important; top: 0px !important; left: 0px !important; background-color: transparent !important; z-index: 2147483637!important");
this.loadHtmlInIframe(document,b,a)}},g={_window:d.top,_doc:d.top.document,installInitiated:!1,validFile:/d3nekkt1lmmhms|printfriendly\.com|printnicer\.com|algo\.js|printfriendly\.js|core\.js/,setVars:function(){this._window.frames["pf-core"]&&this._window.frames["pf-core"].document&&(this._window=this._window.frames["pf-core"],this._doc=this._window.document)},install:function(){if(this.installInitiated)return!0;var a;a=d.JSON&&d.JSON.stringify?"//cdn.ravenjs.com/1.1.11/raven.min.js":e.config.hosts.cdn+
"/javascripts/raven/1.1.11/json_raven.min.js";this.installInitiated=!0;this.setVars();var b=this._doc.createElement("script"),c=this._doc.getElementsByTagName("script")[0];b.src=a;c.parentNode.appendChild(b);this.wait()},wait:function(){if(!this._window.Raven)return setTimeout(function(){g.wait()},100);this.configure();this.pushExistingErrors()},configure:function(){this._window.Raven.config("https://4b3437355eed4d3abf6ee3a5fea7aeca@app.getsentry.com/22091",{dataCallback:function(a){var b;try{b=a.stacktrace.frames[0],
b.filename.match(g.validFile)&&"onload"!==b["function"]||a.stacktrace.frames.shift()}catch(c){}return a},shouldSendCallback:function(a){return a&&a.extra&&a.extra.file||a&&a.culprit&&a.culprit.match(g.validFile)?!0:!1}}).install()},sendError:function(a,b){b="undefined"!==typeof b?{file:b.file,ignore:b.ignore}:{file:"printfriendly.js"};"production"===e.config.environment&&this._window.Raven.captureException(a,{extra:b})},pushExistingErrors:function(){for(var a=0;a<e.errors.length;a++)this.sendError(e.errors[a].err,
e.errors[a].opts)},log:function(a,b){b=b||{file:"printfriendly.js"};try{this._window.Raven?this.sendError(a,b):(e.errors.push({err:a,opts:b}),this.install(),e.messages.push(a.name+" : "+a.message),e.messages.push(a.stack))}catch(c){}}};e.exTracker=g;return e}(window),priFri=pfMod;"algo"===window.name||"pf-core"===window.name||pfMod.initialized||pfMod.init(window.pfOptions);

